// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvXwN9QCqtecZx2r0qSJ9DPgXTUVddf_Y',
    appId: '1:1044667575116:web:c532d0f64bb94d51447de9',
    messagingSenderId: '1044667575116',
    projectId: 'flutter-firebase-dersler-cd2af',
    authDomain: 'flutter-firebase-dersler-cd2af.firebaseapp.com',
    storageBucket: 'flutter-firebase-dersler-cd2af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzHOr9hBl3neWvymM4T6_WI1wO4LZEkKM',
    appId: '1:1044667575116:android:ca19ee7aad2bd09b447de9',
    messagingSenderId: '1044667575116',
    projectId: 'flutter-firebase-dersler-cd2af',
    storageBucket: 'flutter-firebase-dersler-cd2af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUVOEnS0adAwOvU9bTHAHQ6hCRVC9jZoQ',
    appId: '1:1044667575116:ios:e8003ec4819729ac447de9',
    messagingSenderId: '1044667575116',
    projectId: 'flutter-firebase-dersler-cd2af',
    storageBucket: 'flutter-firebase-dersler-cd2af.appspot.com',
    iosClientId: '1044667575116-ifs75ikb1kqq4ki5lqqigk0l2503omjo.apps.googleusercontent.com',
    iosBundleId: 'com.mahmutcanyazlak.flutterFirebaseDersleri',
  );
}
